### ISSUE TITLE
Same as Color Deducto with few differences.

### ISSUE THREAD

**Issue by chimosky** [walterbender/deducto#9]
This activity looks pretty much as [Color Deducto](https://github.com/sugarlabs/colordeducto) with very few non functional differences, I've noticed difference in `activity.info` fields, square shaped colour patterns in `Color Deducto` and circular shaped colour patterns in `Deducto`.

I think they should be merged.

@quozl @walterbender

**Comment by quozl** [comment]
http://lists.sugarlabs.org/archive/sugar-devel/2009-October/020298.html was one of the original announcements in 2009.  They were always separate activities.  Both repositories here have history starting in 2012.  The repositories may be mislabelled.  I suggest looking through the bundles of previous versions to check if that happened.  There are also repositories on http://git.sugarlabs.org/

**Comment by chimosky** [comment]
@walterbender has clarified the differences between both.
